name: chat_mate_messanger
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  badges: ^3.1.2
  chat_bubbles: ^1.5.0
  cloud_firestore: ^4.10.0
  firebase_auth: ^4.11.0
  firebase_core: ^2.18.0
  firebase_database: ^10.3.0
  firebase_messaging: ^14.7.0
  firebase_storage: ^11.3.0
  flutter:
    sdk: flutter
  flutter_app_badger: ^1.5.0
  flutter_background: ^1.2.0
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^16.1.0
  flutter_story_view: ^0.0.3
  flutter_svg: ^2.0.7
  flutter_webrtc: ^0.9.45
  font_awesome_flutter: ^10.6.0
  get: ^4.6.6
  google_fonts: ^6.1.0
  http: ^1.1.0
  loading_animation_widget: ^1.2.0+4
  shared_preferences: ^2.2.2
  timeago: ^3.5.0
  uuid: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
        - assets/images/
        - assets/icons/
        - assets/memoji/
        - .env
